import { LayoutDashboard, BarChart3, UserCircle2, Map, Trello, Sparkles, DollarSign, Calculator, Vote, UserPlus, Users, Truck, Scale, Shield, Settings as SettingsIcon, UserCircle, SquareStack, Leaf } from 'lucide-react';
import type { ModuleDefinition, ModuleKey, ModulePlan, ModuleStateMap } from '../types';

const moduleDefinitions: ModuleDefinition[] = [
  {
    key: 'dashboard',
    label: 'Visão Geral',
    description: 'Resumo executivo com KPIs e alertas críticos do comitê.',
    icon: LayoutDashboard,
    plan: 'Starter',
    defaultEnabled: true,
    showInNavigation: true,
    gateable: false,
  },
  {
    key: 'analytics',
    label: 'Analytics',
    description: 'Painéis de marketing digital, alcance e engajamento.',
    icon: BarChart3,
    plan: 'Growth',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'crm',
    label: 'CRM',
    description: 'Gestão de apoiadores, follow-up e exportações.',
    icon: UserCircle2,
    plan: 'Starter',
    defaultEnabled: true,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'agenda',
    label: 'Agenda',
    description: 'Planejamento de produção com automações logísticas.',
    icon: Map,
    plan: 'Growth',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'canvas',
    label: 'Spaces',
    description: 'Canvas infinito com mapas em escala e múltiplos projetos.',
    icon: SquareStack,
    plan: 'Scale',
    defaultEnabled: true,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'marketing',
    label: 'Marketing',
    description: 'Quadro Kanban da operação criativa integrada ao financeiro.',
    icon: Trello,
    plan: 'Starter',
    defaultEnabled: true,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'marketingAdvanced',
    label: 'Mkt Digital',
    description: 'Automação de mídia paga, criativos e IA generativa.',
    icon: Sparkles,
    plan: 'Scale',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'finance',
    label: 'Financeiro',
    description: 'Controle financeiro com OCR e conciliação.',
    icon: DollarSign,
    plan: 'Starter',
    defaultEnabled: true,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'advancedFinance',
    label: 'Fin. Avançado',
    description: 'Prestação de contas, limites TSE e integrações bancárias.',
    icon: DollarSign,
    plan: 'Scale',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'accounting',
    label: 'Contábil IA',
    description: 'Assistente fiscal para prestação de contas, limites e relatórios.',
    icon: Calculator,
    plan: 'Scale',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'polls',
    label: 'Pesquisas',
    description: 'Central de pesquisas com dashboards e insights.',
    icon: Vote,
    plan: 'Growth',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'volunteers',
    label: 'Voluntários',
    description: 'Organização e ativação da militância de rua.',
    icon: UserPlus,
    plan: 'Growth',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'team',
    label: 'Equipe',
    description: 'Time interno com status, contatos e atribuições.',
    icon: Users,
    plan: 'Starter',
    defaultEnabled: true,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'fleet',
    label: 'Frota',
    description: 'Controle de veículos, abastecimentos e rotas.',
    icon: Truck,
    plan: 'Scale',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'legal',
    label: 'Jurídico',
    description: 'Gestão de pareceres, riscos e notificações legais.',
    icon: Scale,
    plan: 'Growth',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'compliance',
    label: 'Compliance',
    description: 'Checklist normativo e auditoria contínua.',
    icon: Shield,
    plan: 'Scale',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'staffManager',
    label: 'Staff Manager',
    description: 'Credenciamento blindado, deployment e gestão operacional de equipe.',
    icon: Shield,
    plan: 'Growth',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'ecoGestao',
    label: 'Eco-Gestão',
    description: 'Sustentabilidade, gestão de resíduos, eficiência energética e carbon footprint.',
    icon: Leaf,
    plan: 'Scale',
    defaultEnabled: false,
    showInNavigation: true,
    gateable: true,
  },
  {
    key: 'settings',
    label: 'Configurações',
    description: 'Parametros gerais, times e preferências da campanha.',
    icon: SettingsIcon,
    plan: 'Starter',
    defaultEnabled: true,
    showInNavigation: true,
    gateable: false,
  },
  {
    key: 'profile',
    label: 'Perfil do Evento',
    description: 'Identidade visual, patrocinadores e canais oficiais.',
    icon: UserCircle,
    plan: 'Starter',
    defaultEnabled: true,
    showInNavigation: false,
    gateable: false,
  },
];

export const MODULE_DEFINITIONS = moduleDefinitions;

export const MODULE_MAP: Record<ModuleKey, ModuleDefinition> = moduleDefinitions.reduce(
  (acc, module) => {
    acc[module.key] = module;
    return acc;
  },
  {} as Record<ModuleKey, ModuleDefinition>
);

export const DEFAULT_ENABLED_MODULES: ModuleStateMap = moduleDefinitions.reduce(
  (acc, module) => {
    acc[module.key] = module.defaultEnabled;
    return acc;
  },
  {} as ModuleStateMap
);

export const PLAN_ORDER: ModulePlan[] = ['Starter', 'Growth', 'Scale'];
